### PR TITLE
Update appendix.md

### PR DESCRIPTION
**Pull request by yazeedalrubyli**

### CODE REVIEW

**Comment by vandenbrande** [comment]
Hi, Thank you for contacting us.  This is a confirmation that your e-mail has been received. We will reply to your e-mail within 24-48 hours. Have a nice day!  Best regards,  ArduinoSensors.nl

**Comment by brannondorsey** [comment]
Thanks!

**Comment by yazeedalrubyli** [comment]
You're welcome, It's was nothing ;)

**Review by nijasm98-ai — COMMENTED** [review]
I want hack my company wi fi

**Pull request merged**
