### PR TITLE
Add instructions on how to use on OS X

### PR DESCRIPTION
**Pull request by harshpatel991**
I just added it as another README file, feel free to modify or move it around :)

### CODE REVIEW

**Comment by brannondorsey** [comment]
You are brilliant :1st_place_medal:
Thanks so much for this, I will include it in the repo tonight :+1:

**Comment by brannondorsey** [comment]
I'm testing ths with OSX 10.10, and things are working great up through step 4 of "Capture a 4-way handshake". Once I finish scanning using the Wireless Diagnostics scanner I don't see any `*.wcap` or similar file in `/var/tmp`. Is there another location they might be saved? Also, do you get any kind of dialogue or message once scanning is stopped? Because I don't but would sort of expect to.

**Comment by brannondorsey** [comment]
Aha, for me it saves the `.wcap` on the Desktop. Strange.

**Comment by harshpatel991** [comment]
@brannondorsey Odd, my dialogue box says that it'll go directly to /var/tmp.  Image

I also don't get a message after hitting stop.

**Comment by brannondorsey** [comment]
Migrated this into the appendix and linked to it from the main tutorial. I've updated [`naive-hashcat`](https://github.com/brannondorsey/naive-hashcat) with your changes as well to streamline the process a bit. If you have a second, would you mind testing? It seems to be working well for me. Thanks again for this contribution!

**Comment by harshpatel991** [comment]
Tested it out, works. Thanks for making those changes to naive-hashcat

**Comment by JaosnHsieh** [comment]
> @brannondorsey Odd, my dialogue box says that it'll go directly to /var/tmp. Image
> 
> I also don't get a message after hitting stop.

Second this, didn't get `*.wcap` file on `/var/tmp` on `v11.12.3` macos

**Pull request merged**
